<?php 
        // todo: do this in the core class
        $hasTodo = FALSE;
        if (count($vars['section']->getParameters()) > 0) {
            foreach ($vars['section']->getParameters() as $parameter) { 
                if (strpos($parameter->getName(), 'todo') !== FALSE || strpos($parameter->getDescription(), '@todo') !== FALSE) {
                    $hasTodo = TRUE;
                }
            }
        }
?>

<div class="styleguide__block" id="r<?php echo $vars['section']->getReference(); ?>">
    <?php 
        $level = $vars['section']->getDepth()+1;
    ?>
    <h<?php echo $level ?> class="styleguide__block__header">
        <span class="styleguide__block__title"><?php echo $vars['section']->getDescriptionTitle(); ?></span>
        <?php if ($vars['section']->getExperimental()) { ?><span class="label label-danger">Experimental!</span> <?php } ?>
        <?php if ($vars['section']->getDeprecated()) { ?><span class="label label-default">Deprecated!</span> <?php } ?>
        <?php if ($hasTodo) { ?><span class="label label-warning">ToDo</span> <?php } ?>
    </h<?php echo $level ?>>

    <div class="styleguide__block__description">
        <p><?php echo nl2br($vars['section']->getDescriptionText()); ?></p>
        <?php
            if (count($vars['section']->getModifiers()) > 0) {
        ?>
            <ul class="styleguide__block__modifiers">
                <?php foreach ($vars['section']->getModifiers() as $modifier) { ?>
                    <li>
                        <span class="styleguide__block__modifier-name <?php echo ($modifier->isExtender()) ? 'styleguide__modifier-name--extender' : ''; ?>">
                            <?php echo $modifier->getName(); ?>
                        </span>
                            <?php if ($modifier->isExtender()) { ?>
                                @extend
                                <span class="styleguide__block__modifier-name"><?php echo $modifier->getExtendedClass(); ?></span>
                            <?php } ?>
                        <?php if ($modifier->getDescription()) { ?>
                            - <?php echo $modifier->getDescription(); ?>
                        <?php } ?>
                    </li>
                <?php } ?>
            </ul>
        <?php } ?>

        
    </div>


    <?php
        if ($vars['section']->hasMarkup()) {
            $src = 'index.php?preview&ref='.$vars['section']->getReference().'&src='.$vars['styleguide']->getSource()->getKey();
            $id = str_replace(".", "_", $vars['section']->getReference() . $vars['styleguide']->getSource()->getKey());
    ?>

    <nav class="styleguide__block__tabs">
        <ul class="nav nav-tabs">
            <li class="active styleguide__block__tabs__preview"><a title="Preview" href="#styleguidePreview<?php echo$id; ?>"><span class="fa fa-eye"></span></a></li>
            <li class="styleguide__block__tabs__markup"><a href="#styleguideMarkup<?php echo$id; ?>"><span class="fa fa-code"></span></a></li>
            <li class="styleguide__block__tabs__info"><a href="#styleguideInfo<?php echo$id; ?>"><span class="fa fa-info-circle"></span></a></li> 
            <!-- <li><a href="#styleguideComments<?php echo$id; ?>">Notes (ToDo)</a></li> -->
        </ul>
    </nav>

    <div class="tab-content">
        <div class="tab-pane active styleguide__block__preview" id="styleguidePreview<?php echo $id; ?>">
            <div class="styleguide__block__preview__frame" data-preview="frame">
                <iframe scrolling="no" src="about:blank" data-src="<?php echo $src ?>" name="preViewFrame_<?php echo $id ?>"></iframe>
                <noscript>
                    <iframe scrolling="no" src="<?php echo $src ?>"></iframe>
                </noscript>
            </div>
            <ul class="styleguide__block__preview__actions">
                <li>
                    <a title="Inspect in new window" class="styleguide__block__preview__enlarge" href="<?php echo $src ?>" target="_blank"><span class="fa fa-clone"></span></a>
                </li>
                <li>
                    <a title="Refresh" class="styleguide__block__preview__reload" target="preViewFrame_<?php echo $id ?>" href="<?php echo $src ?>" target="_blank"><span class="fa fa-refresh"></span></a>
                </li>
            </ul>
        </div>

        <div class="tab-pane styleguide__block__html" id="styleguideMarkup<?php echo$id; ?>">
            <pre class="styleguide__block__code"><code class="html"><?php echo htmlentities($vars['section']->getMarkupNormal('{class}')); ?></code></pre>
        </div>

        <div class="tab-pane styleguide__block__info" id="styleguideInfo<?php echo$id; ?>">
            <dl class="dl-horizontal">
                <dt>File:</dt>
                <dd><?php echo $vars['section']->getFilename(); ?></dd>
                <dt>Compatibility:</dt>
                <dd><?php echo $vars['section']->getCompatibility() ? nl2br($vars['section']->getCompatibility()) : '-'; ?></dd>
                <dt>Partial:</dt>
                <dd><?php echo $vars['section']->getPartial() ? $vars['section']->getPartial() : '-' ?></dd>
                <dt>Tags</dt>
                <dd>
                <?php
                    if (count($vars['section']->getParameters()) > 0 || $vars['section']->getDeprecated() || $vars['section']->getExperimental()) {
                ?>
                    <ul class="styleguide__block__parameters">
                        <?php 
                        if (count($vars['section']->getParameters()) > 0) {
                        foreach ($vars['section']->getParameters() as $parameter) { ?>
                            <li>
                                <span class="styleguide__block__parameter-name">
                                    <?php echo $parameter->getName(); ?>
                                </span>
                                <?php if ($parameter->getDescription()) { ?>
                                    <?php echo $parameter->getDescription(); ?>
                                <?php } ?>
                            </li>
                        <?php }
                        } 
                        ?>
                        <?php if ($vars['section']->getDeprecated()) { ?>
                        <li class="styleguide__block__parameter-experimental">
                            <span class="styleguide__block__parameter-name">Deprecated!</span>
                            <?php echo $vars['section']->getDeprecated() ?>
                        </li>
                        <?php } ?>
                        <?php if ($vars['section']->getExperimental()) { ?>
                        <li class="styleguide__block__parameter-experimental">
                            <span class="styleguide__block__parameter-name">Experimental!</span>
                            <?php echo $vars['section']->getExperimental() ?>
                        </li>
                        <?php } ?>
                    </ul>
                <?php } else { ?>
                    -
                <?php }  ?>
                </dd>
                <dt>Validation (HTML)</dt>
                <dd>
                    <ul class="styleguide__validationresults" data-validation="results"></ul>
                </dd>

            </dl>
        </div>
    </div>
    <?php
        }
    ?>
</div>
