<ul>
    <li><a href="<?= $_SERVER['SCRIPT_NAME'] ?>">Home </a></li>
    <?php
        foreach ($Styleguide->getSources() as $source) {
            echo '<li><span>'. $source->getName() .'</span><ul>';
            foreach ($source->getParser()->getTopLevelSections() as $topLevelSection) {
                echo '<li>
                    <a href="'.\Thopra\Styleguide\Utility\UriUtility::section($topLevelSection->getReference(),$source->getKey()).'" title="'.$topLevelSection->getTitle().'">' .
                        $topLevelSection->getDescriptionTitle() .
                    '</a>' ;
                   
                echo "</li>";
            }
            echo "</ul></li>";
        }
    ?>
    </ul>