<nav role="main" id="styleguideSections" class="styleguide__nav sidr left" >

    <span class="styleguide__nav__brand">Styleguide <em>Viewer 2</em></span>

    <ul>
    <li><a href="index.php">Home </a></li>
    <?php
        foreach ($Styleguide->getSources() as $source) {
            echo '<li><span>'. $source->getName() .'</span><ul>';
            foreach ($source->getParser()->getTopLevelSections() as $topLevelSection) {
                echo '<li>
                    <a href="index.php?ref='.$topLevelSection->getReference().'&src='.$source->getKey().'" title="'.$topLevelSection->getTitle().'">' .
                        $topLevelSection->getDescriptionTitle() .
                    '</a>' ;
                    $childSections = $source->getParser()->getSectionChildren($topLevelSection->getReference());
                    if (is_array($childSections) && count($childSections) && $Styleguide->getRef() == $topLevelSection->getReference()) {
                        echo '<ul class="nav">';
                            foreach ($childSections as $key => $navSection) {
                                echo '<li><a href="#r' . $navSection->getReference() . '">' . $navSection->getDescriptionTitle() .'</a>';
                            }
                        echo '</ul>';
                    }
                echo "</li>";
            }
            echo "</ul></li>";
        }
    ?>
    </ul>
</nav>
