<div class="styleguide-preview__preview">
	<div class="styleguide-preview_element">
	    <?php echo $vars['section']->getMarkupNormal(); ?>
	</div>
<?php foreach ($vars['section']->getModifiers() as $modifier) { ?>
    <div class="styleguide-preview__element styleguide-preview__element--modifier <?php ($modifier->isExtender()) ? 'styleguide-preview__element--extender' : ''; ?>">
        <span class="styleguide-preview__element__modifier-label <?php echo ($modifier->isExtender()) ? 'styleguide-preview__element__modifier-label--extender' : ''; ?>"><?php echo $modifier->getName(); ?></span>
       	<?php echo $modifier->getExampleHtml(); ?>
    </div>
<?php } ?>
</div>