<!DOCTYPE html>
<html class="styleguide-preview">
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>Styleguide Preview</title>
    <?php 

    foreach ($Styleguide->getSource()->getCSSResources() as $resource) {
    	echo '<link rel="stylesheet" type="text/css" href="'.$resource.'" />';
    }

    ?>
    
    <link rel="stylesheet" href="guidance/Assets/css/preview.css" />

</head>
<body>

	<?php $Styleguide->displayTemplate('Preview', $vars);

    foreach ($Styleguide->getSource()->getJSResources() as $resource) {
        echo '<script src="'.$resource.'"></script>';
    }

     ?>

</body>
</html> 