<!DOCTYPE html>
<html class="styleguide">
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title><?php echo $Styleguide->getTitle() ?> - Guidance Styleguide Viewer</title>
    <link rel="stylesheet" href="guidance/Assets/css/styleguide.css" />

</head>
<body class="pending sidr-open">
<div class="styleguide__root">

	<div class="styleguide__toolbar">
		<a class="styleguide__toolbar__menu" href="#styleguideSections"><span></span></a>
		<ul>
			<li class="styleguide__viewports">
				<ul>
					<li class="styleguide__viewports__xs" data-viewport="0" data-width="310"></li>
					<li class="styleguide__viewports__sm" data-viewport="767" data-width="767"></li>
					<li class="styleguide__viewports__md" data-viewport="980" data-width="980"></li>
					<li class="styleguide__viewports__lg" data-viewport="1140" data-width="100%"></li>
				</ul>
			</li>
			<li class="styleguide__enlarge"></li>
		</ul>

		<div class="styleguide__viewportrange">
			  <input type="text" id="styleguideViewportWidth" readonly>
			  <div id="styleguideViewportRange"></div>
		</div>
	</div>

	<?php $Styleguide->displayTemplate('Menu'); ?>

	<div class="styleguide__wrapper">

		<?php $Styleguide->displayTemplate($vars['template'], $vars); ?>

	    <footer>
	    <?php echo $Styleguide->getTitle(); ?> - <?php echo $Styleguide->lastModified(); ?>
	    </p>
	    </footer>

	</div>
	<div class="styleguide__loader"><div class="styleguide__loader__icon"><span class="fa fa-cog fa-spin fa-fw"></span></div></div>
</div>

<script src="guidance/Assets/contrib/jquery/dist/jquery.min.js"></script>
<script src="guidance/Assets/contrib/jquery-ui/jquery-ui.min.js"></script>
<script src="guidance/Assets/contrib/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="guidance/Assets/contrib/sidr/jquery.sidr.min.js"></script>
<script src="guidance/Assets/contrib/highlight/highlight.pack.js"></script>
<script src="guidance/Assets/js/styleguide.js"></script>

</body>
</html> 